apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: default
data:
  Feature-Policy: microphone 'none'; geolocation 'none'; payment 'none'
  Referrer-Policy: same-origin
  X-Content-Type-Options: nosniff
  hsts: "True"
  proxy-body-size: 50m
  real_ip_header: X-Forwarded-For
  server-tokens: "False"