apiVersion: v1
kind: Secret
metadata:
  name: oci-compliant-registry
  labels:
{{- include "csis.labels" . | trim | nindent 4 }}
    component: dockerconfigjson
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" . }}
---
apiVersion: v1
data:
  MAIL_PWD: {{ printf .Values.mail.emailPassword | b64enc }}
  MAIL_USER_NAME: {{ printf .Values.mail.emailAccount | b64enc }}
kind: Secret
metadata:
  name: mail-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "csis.labels" . | trim | nindent 4 }}
type: Opaque
---
apiVersion: v1
data:
  rails_master_key: {{ printf .Values.csis.masterKey | b64enc }}
kind: Secret
metadata:
  name: rails-secrets
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "csis.labels" . | trim | nindent 4 }}
type: Opaque
