apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Release.Name }}-redis
{{- include "csis.labels" . | trim | nindent 4 }}
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    component: {{ .Release.Name }}-redis
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Release.Name }}-db
{{- include "csis.labels" . | trim | nindent 4 }}
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    component: {{ .Release.Name }}-db
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Release.Name }}-app
{{- include "csis.labels" . | trim | nindent 4 }}
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - protocol: TCP
    port: 8002 #Port de sortie du pod
    targetPort: 3000 #Service où tourne le server rails
  selector:
    component: {{ .Release.Name }}-app
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Release.Name }}-queue
{{- include "csis.labels" . | trim | nindent 4 }}
  name: {{ .Release.Name }}-queue
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    component: {{ .Release.Name }}-queue
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Release.Name }}-scheduler
{{- include "csis.labels" . | trim | nindent 4 }}
  name: {{ .Release.Name }}-scheduler
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    component: {{ .Release.Name }}-scheduler
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Release.Name }}-db-admin
{{- include "csis.labels" . | trim | nindent 4 }}
  name: {{ .Release.Name }}-db-admin
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - protocol: TCP
    port: 8081 #Port de sortie du pod
    targetPort: 80 #Service où tourne le pgadmin
  selector:
    component: {{ .Release.Name }}-db-admin
status:
  loadBalancer: {}
