apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: oci-compliant-registry
metadata:
  name: {{ .Values.csis.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "csis.labels" . | trim | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ include "csis.name" . }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}